// <auto-generated />
using System;
using AvaloniaApplication.DAL2;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AvaloniaApplication.DAL2.Migrations
{
    [DbContext(typeof(BlankDbContext))]
    partial class BlankDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AvaloniaApplication.DAL2.PlaneBoard", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("PlaneBoardNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PlaneType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PlaneType", "PlaneBoardNo")
                        .IsUnique();

                    b.ToTable("PlaneBoard", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1m,
                            PlaneBoardNo = "004",
                            PlaneType = "SU-27"
                        },
                        new
                        {
                            Id = 2m,
                            PlaneBoardNo = "16",
                            PlaneType = "MIG-29"
                        });
                });

            modelBuilder.Entity("AvaloniaApplication.DAL2.PlaneFlight", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(20,0)");

                    b.Property<DateTime>("FlightDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FlightNo")
                        .HasColumnType("integer");

                    b.Property<short>("FlightSmena")
                        .HasColumnType("smallint");

                    b.Property<string>("PilotName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("PlaneBoardId")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("Id");

                    b.HasIndex("PlaneBoardId", "FlightDate", "FlightSmena", "FlightNo")
                        .IsUnique();

                    b.ToTable("PlaneFlight", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1m,
                            FlightDate = new DateTime(2010, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FlightNo = 1,
                            FlightSmena = (short)1,
                            PilotName = "Иванов",
                            PlaneBoardId = 1m
                        },
                        new
                        {
                            Id = 2m,
                            FlightDate = new DateTime(2010, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FlightNo = 2,
                            FlightSmena = (short)1,
                            PilotName = "Иванов",
                            PlaneBoardId = 1m
                        },
                        new
                        {
                            Id = 3m,
                            FlightDate = new DateTime(2017, 6, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FlightNo = 6,
                            FlightSmena = (short)1,
                            PilotName = "Петров",
                            PlaneBoardId = 1m
                        },
                        new
                        {
                            Id = 4m,
                            FlightDate = new DateTime(2010, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FlightNo = 1,
                            FlightSmena = (short)1,
                            PilotName = "Сидоров",
                            PlaneBoardId = 2m
                        });
                });

            modelBuilder.Entity("AvaloniaApplication.DAL2.PlaneFlight", b =>
                {
                    b.HasOne("AvaloniaApplication.DAL2.PlaneBoard", "PlaneBoard")
                        .WithMany("Flights")
                        .HasForeignKey("PlaneBoardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlaneBoard");
                });

            modelBuilder.Entity("AvaloniaApplication.DAL2.PlaneBoard", b =>
                {
                    b.Navigation("Flights");
                });
#pragma warning restore 612, 618
        }
    }
}
