// <auto-generated />
using System;
using AvaloniaApplication.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AvaloniaApplication.DAL.Migrations
{
    [DbContext(typeof(BlankDbContext))]
    partial class BlankDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.11");

            modelBuilder.Entity("AvaloniaApplication.DAL.PlaneBoard", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("PlaneBoardNo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PlaneType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PlaneType", "PlaneBoardNo")
                        .IsUnique();

                    b.ToTable("PlaneBoard", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1ul,
                            PlaneBoardNo = "004",
                            PlaneType = "SU-27"
                        },
                        new
                        {
                            Id = 2ul,
                            PlaneBoardNo = "16",
                            PlaneType = "MIG-29"
                        });
                });

            modelBuilder.Entity("AvaloniaApplication.DAL.PlaneFlight", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FlightDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("FlightNo")
                        .HasColumnType("INTEGER");

                    b.Property<short>("FlightSmena")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PilotName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<ulong>("PlaneBoardId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PlaneBoardId", "FlightDate", "FlightSmena", "FlightNo")
                        .IsUnique();

                    b.ToTable("PlaneFlight", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1ul,
                            FlightDate = new DateTime(2010, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FlightNo = 1,
                            FlightSmena = (short)1,
                            PilotName = "Иванов",
                            PlaneBoardId = 1ul
                        },
                        new
                        {
                            Id = 2ul,
                            FlightDate = new DateTime(2010, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FlightNo = 2,
                            FlightSmena = (short)1,
                            PilotName = "Иванов",
                            PlaneBoardId = 1ul
                        },
                        new
                        {
                            Id = 3ul,
                            FlightDate = new DateTime(2017, 6, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FlightNo = 6,
                            FlightSmena = (short)1,
                            PilotName = "Петров",
                            PlaneBoardId = 1ul
                        },
                        new
                        {
                            Id = 4ul,
                            FlightDate = new DateTime(2010, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FlightNo = 1,
                            FlightSmena = (short)1,
                            PilotName = "Сидоров",
                            PlaneBoardId = 2ul
                        });
                });

            modelBuilder.Entity("AvaloniaApplication.DAL.PlaneFlight", b =>
                {
                    b.HasOne("AvaloniaApplication.DAL.PlaneBoard", "PlaneBoard")
                        .WithMany("Flights")
                        .HasForeignKey("PlaneBoardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlaneBoard");
                });

            modelBuilder.Entity("AvaloniaApplication.DAL.PlaneBoard", b =>
                {
                    b.Navigation("Flights");
                });
#pragma warning restore 612, 618
        }
    }
}
